name:                hastext
version:             0.1.0.0
synopsis:            Haskell Word2Vec implementation based on FastText
description:         See README at <https://github.com/nnwww/hastext#readme>
github:              nnwww/hastext
license:             MIT
license-file:        LICENSE
author:              Haruka Oikawa
maintainer:          johndororo@gmail.com
copyright:           2017 Haruka Oikawa
category:            Machine learning
build-type:          Simple
extra-source-files:  README.md

data-files:          data/*.txt
ghc-options:         -Wall
_run-ghc-options: &run -threaded -rtsopts -with-rtsopts=-N

dependencies:
  - base >= 4.7 && < 5
  - array >= 0.5
  - bytestring >= 0.10
  - binary >= 0.8
  - text >= 1.2
  - text-show >= 3.4.1.1
  - unordered-containers >= 0.2
  - vector >= 0.11
  - vector-algorithms >= 0.7
  - conduit >= 1.2
  - conduit-combinators >= 1.1
  - mwc-random >= 0.13
  - resourcet >= 1.1
  - hmatrix >= 0.1
  - hashable >= 1.2
  - mtl >= 2.2
  - filepath >= 1.4
  - directory >= 1.3
  - async >= 2.1
  - safe-exceptions >= 0.1

library:
  source-dirs: src
  exposed-modules:
    - WordEmbedding.HasText.Args
    - WordEmbedding.HasText.Dict
    - WordEmbedding.HasText.Model
    - WordEmbedding.HasText
  other-modules:
    - WordEmbedding.HasText.Type

executables:
  hastext:
    source-dirs: app
    main: Main.hs
    ghc-options: *run
    dependencies:
      - optparse-applicative >= 0.13.2
      - hastext

tests:
  spec:
    source-dirs:
      - test
    main: Spec.hs
    ghc-options: *run
    other-modules:
      - TestDict
      - TestData
      - Paths_hastext
    dependencies:
      - hastext
      - doctest
      - tasty >= 0.11.2.1
      - tasty-hunit >= 0.9.2
