name:                hastext
version:             0.1.0.0
synopsis:            Haskell Word2Vec implementation based on FastText
description:         See README at <https://github.com/nnwww/hastext#readme>
github:              nnwww/hastext
license:             MIT
license-file:        LICENSE
author:              Haruka Oikawa
maintainer:          johndororo@gmail.com
copyright:           2017 Haruka Oikawa
category:            Machine learning
build-type:          Simple
extra-source-files:  README.md

# coupuses for test or benchmark are placed here.
data-files:
  - data/*.txt
  - data/text8
  - data/text8s/*

ghc-options: -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates

# see https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/profiling.html#profiling-parallel-and-concurrent-programs
ghc-prof-options:
  - -fno-prof-count-entries
  - -O2

dependencies:
  - base >= 4.7 && < 5
  - array >= 0.5
  - async >= 2.1
  - binary >= 0.8
  - binary-orphans >= 0.1.6
  - bytestring >= 0.10
  - conduit >= 1.2
  - conduit-combinators >= 1.1
  - deepseq >= 1.4.2
  - directory >= 1.3
  - filepath >= 1.4
  - hashable >= 1.2
  - mtl >= 2.2
  - mutable-containers >= 0.3.3
  - mwc-random >= 0.13
  - resourcet >= 1.1
  - safe-exceptions >= 0.1
  - text >= 1.2
  - text-show >= 3.4.1.1
  - terminal-progress-bar >= 0.1.1.1
  - unordered-containers >= 0.2
  - vector >= 0.11
  - vector-algorithms >= 0.7

library:
  source-dirs: src
  exposed-modules:
    - WordEmbedding.HasText
    - WordEmbedding.HasText.Args
    - WordEmbedding.HasText.Dict
    - WordEmbedding.HasText.Model
  other-modules:
    - WordEmbedding.HasText.Internal.Type
    - WordEmbedding.HasText.Internal.Strict.HasText
    - WordEmbedding.HasText.Internal.Strict.Model
    - WordEmbedding.HasText.Internal.Strict.MVectorOps

executables:
  hastext:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    ghc-prof-options:
      - -fno-prof-count-entries
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts="-N -p"
    dependencies:
      - optparse-applicative >= 0.13.2
      - hastext

tests:
  spec:
    source-dirs:
      - test
    main: Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    other-modules:
      - Paths_hastext
      - TestDict
      - TestData
      - TestModel
    dependencies:
      - hastext
      - doctest
      - tasty >= 0.11.2.1
      - tasty-hunit >= 0.9.2

benchmarks:
  core:
    source-dirs: bench
    main: Bench.hs
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hastext
      - criterion >= 1.1.4
